cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

game/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$',views.post_list, name='post_list'),
	url(r'^late/$',views.post_new, name='post_new'),
	url(r'^omen/$',views.post_list3, name='post_list3'),
	url(r'^right/$',views.post_list4, name='post_list4'),
	url(r'^end/$',views.post_list5, name='post_list5'),
	url(r'^next/$',views.post_list6, name='post_list6'),
	url(r'^zero/$',views.post_list7, name='post_list7'),
	url(r'^orcs/$',views.post_list8, name='post_list8'),
	url(r'^lorenzo/$',views.post_list9, name='post_list9'),
]

npcshop/urls.py
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
url(r'cart/', include('cart.urls', namespace='cart')),
url(r'^gamehome/', include('game.urls', namespace='game')),
url(r'', include('shop.urls',namespace='shop')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.conf.urls import url
from . import views

app_name = 'npcshop'

urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
url(r'^late/$',views.post_new, name='post_new'),
url(r'^omen/$',views.post_list3, name='post_list3'),
	url(r'^right/$',views.post_list4, name='post_list4'),
	url(r'^end/$',views.post_list5, name='post_list5'),
	url(r'^next/$',views.post_list6, name='post_list6'),
	url(r'^zero/$',views.post_list7, name='post_list7'),
	url(r'^orcs/$',views.post_list8, name='post_list8'),
	url(r'^lorenzo/$',views.post_list9, name='post_list9'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

cart/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

game/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

shop/models.py
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse

class Category(models.Model):
    name = models.CharField(max_length=200,db_index=True)
    slug = models.SlugField(max_length=200,db_index=True, unique = True)
class Meta:
            ordering = ('name', )
            verbose_name = 'category'
            verbose_name_plural = 'categories'

def __str__(self):
		return self.name

def get_absolute_url(self):
		return reverse('shop:product_list_by_category', args=[self.slug])

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200,db_index=True)
    slug = models.SlugField(max_length=200,db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

class Meta:
		ordering = ('-created',)
		index_together = (('id','slug'),)

def __str__(self):
		return self.name

def get_absolute_url(self):
		return reverse('shop:product_detail', args=[self.id, self.slug])

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 26)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

shop/forms.py
from django import forms

class NameForm(forms.Form):
    your_name = forms.CharField(label='Shopbuy', max_length=100)

cart/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

game/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.
def post_list(request):
    return render(request, 'game/gamehome.html', {})

def post_new(request):
    return render(request, 'game/late.html', {})

def post_list3(request):
    return render(request, 'game/omen.html', {})

def post_list4(request):
    return render(request, 'game/right.html', {})

def post_list5(request):
    return render(request, 'game/end.html', {})

def post_list6(request):
    return render(request, 'game/next.html', {})

def post_list7(request):
    return render(request, 'game/zero.html', {})

def post_list8(request):
    return render(request, 'game/ohmygod.html', {})

def post_list9(request):
    return render(request, 'game/lorenzo.html', {})

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    context = {
        'category': category,
        'categories': categories,
        'products': products
    	}
    return render(request, 'npcshop/product/list.html', context)


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    context = {
        'product': product,
        'cart_product_form': cart_product_form
    	}
    return render(request, 'npcshop/product/detail.html', context)

def post_list(request):
    return render(request, 'game/gamehome.html', {})

def post_new(request):
    return render(request, 'game/late.html', {})

def post_list3(request):
    return render(request, 'game/omen.html', {})

def post_list4(request):
    return render(request, 'game/right.html', {})

def post_list5(request):
    return render(request, 'game/end.html', {})

def post_list6(request):
    return render(request, 'game/next.html', {})

def post_list7(request):
    return render(request, 'game/zero.html', {})

def post_list8(request):
    return render(request, 'game/orcs.html', {})

def post_list9(request):
    return render(request, 'game/lorenzo.html', {})

cart/templates/cart/detail.html
{% extends 'npcshop/base.html' %}
{% load static %}
{% block title %}
    Your Shopping Cart
{% endblock %}


{% block content %}
    <div class="container">
        <div class="row" style="margin-top: 6%">
        <h2>Your Shopping Cart
            <span class="badge pull-right">
                {% with totail_items=cart|length %}
                    {% if cart|length > 0 %}
                        My Shopping Order:
                        <a href="{% url "cart:cart_detail" %}" style="color: Gold">
                            {{ total_items }} item {{ total_items|pluralize }},{{ cart.get_total_price }} Gold
                        </a>
                        {% else %}
                        Your cart is empty.
                    {% endif %}
                {% endwith %}
            </span>
        </h2>
            <table class="table table-striped table-hover">
                <thead style="background-color: #5AC8FA">
                    <tr>
                        <th>Image</th>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th>Remove</th>
                        <th>Unit Price</th>
                        <th>Price</th>
                    </tr>
                </thead>
                <tbody>
                {% for item in cart %}
                    {% with product=item.product  %}
                        <tr>
                            <td>
                                <a href="{{ product.get__absolute_url }}">
                                    <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" style="height: 150px; width: auto">
                                </a>
                            </td>
                            <td>{{ product.name }}</td>
                            <td>
                                <form action="{% url "cart:cart_add" product.id %}" method="post">
                                    {% csrf_token %}
                                    {{ item.update_quantity_form.quantity }}
                                    {{ item.update_quantity_form.update }}
                                    <input type="submit" value="Update" class="btn btn-info">
                                </form>
                            </td>
                            <td>
                                <a href="{% url "cart:cart_remove" product.id %}">Remove</a>
                            </td>
                            <td>{{ item.price }} Gold</td>
                            <td>{{ item.total_price }} Gold</td>
                        </tr>
                    {% endwith %}
                {% endfor %}
                <tr style="background-color: #5AC8FA">
                    <td><b>Total</b></td>
                    <td colspan="4"></td>
                    <td colspan="num"><b>{{ cart.get_total_price }} Gold</b></td>
                </tr>
                </tbody>
            </table>
        <p class="text-right">
            <a href="{% url "shop:product_list" %}" class="btn btn-default">Continue Shopping</a>
            <a href="" class="btn btn-primary">Checkout</a>
        </p>
        </div>
    </div>
{% endblock %}

game/templates/game/end.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>PYTHON GAME ARG</title>
<link rel="stylesheet" type="text/css"  href="{% static 'css/gamehome.css' %}">
</head>
<body>
	<h1><font color="red">Riddle me this batman</font></h1>
<div align = "center" class="center">

<p>I am an arrow pointing to the right.</p>
<p>I don't point directions, but i follow procedures</p>
<p>I no longer needed where theres nothing left</p>
<p>previous is my brother, skip is my twin</p>
<p>What am i ?</p>

</div>

<p>Hint: NO HINTS!</p>
</body>
</html>

game/templates/game/gamehome.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>PYTHON GAME ARG</title>
<link rel="stylesheet" type="text/css"  href="{% static 'css/gamehome.css' %}">
</head>
<body>
	<div align = "center" class="center">
	<img src="{% static 'css/img/logo.png'%}">
	</div>

<div align = "center" class="center">
<h1>Welcome to Background Npc's A.R.G</h1>
<h3>What is an A.R.G?</h3>
<hr>
<iframe width="420" height="345" src="https://www.youtube.com/embed/tgbNymZ7vqY">
</iframe>
<hr>
<p>However in my case, it would be just a puzzle solving game.</p>
</div>

<div align ="center">
<p>The game are simple, find the hidden "URL code" and type it in the browser. For example:<p>

<div align = "center" class ="">
	<img src="{% static 'css/img/hint.png'%}">
</div>

<p>Each code will lead you to the next puzzle until you reach the end.</p>
<p>Good Luck!</p>

</div>


</body>
</html>

game/templates/game/late.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>PYTHON GAME ARG</title>
<link rel="stylesheet" type="text/css"  href="{% static 'css/gamehome.css' %}">
</head>
<body>
<h1><font color="red">Good lets begin...</font></h1>

<div class="center">
<h4>“Imagine life as a game in which yu are juggling some five balls in the air. You name them—work, faily, health, friends and spirit…and you’re keeping all of these in the air.You will soon understand that work is a rubber ball. If you drop it, it will bounce back. But the other four balls—family, health, frinds and spirit—are made of glass. If you drop one of these, they will be irrevocably scuffed, marked, nicked, damaged or even shattered. They will never be the same. You must understand that and strive for balace in your life." -Bryan Dyson</h4>
</div>

<p>Hint: read it carefully</p>
</body>
</html>

game/templates/game/lorenzo.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>PYTHON GAME ARG</title>
<link rel="stylesheet" type="text/css"  href="{% static 'css/gamehome.css' %}">
</head>
<body>

<div align = "center" class="center">
<h1><font color="red">CONGRATULATIONS!</font></h1>
<img src="{% static 'css/img/congratz.gif'%}">
<hr>
<h2>Du vann det här dumma spelet, tack för att du spelade!</h2>
<hr>
</div>
</body>
</html>

game/templates/game/next.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>PYTHON GAME ARG</title>
<link rel="stylesheet" type="text/css"  href="{% static 'css/gamehome.css' %}">
</head>
<body>
<h1><font color="red">/watch?v=6b0ftfKFEJg</h1>

<div align = "center" class="center">

<p>/watch?v=Z8SPwT3nQZ8</p>
<p>/watch?v=zpOULjyy-n8</p>
<p>/watch?v=r5yaoMjaAmE</p>
<p>/watch?v=NrI-UBIB8Jk</p>
<p>/watch?v=RSj0mPJsMy0</p>
<p>/watch?v=XpqqjU7u5Yc</p>
<p>/watch?v=WUOtCLOXgm8</p>
<p>/watch?v=dQw4w9WgXcQ</p>
<p>/watch?v=1TxgfbPl9Qg</p>


</div>
<p>Hint:Title</p>
</body>
</html>

game/templates/game/omen.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>PYTHON GAME ARG</title>
<link rel="stylesheet" type="text/css"  href="{% static 'css/gamehome.css' %}">
</head>
<body>
<h1><font color="red">Who's Who</h1>


<div align="center" class="row">
	<div class="column">
		<div class="card">
		<img src="{% static 'css/img/deadpool.png'%}" alt="R">
			<div class="container">
			<span>Ryan Reynolds</span>
			</div>
		</div>
	</div>
	<div class="column">
		<div class="card">
		<img src="{% static 'css/img/BatmanAdamWest.jpg'%}">
			<div class="container">
			<span>Michael Keaton</span>
			</div>
		</div>
	</div>
	<div class="column">
		<div class="card">
		<img src="{% static 'css/img/MagnetoIanMcKellen.png'%}" alt="I">
			<div class="container">
				<span>Ian McKellen</span>
			</div>
		</div>
	</div>
	<div class="column">
		<div class="card">
		<img src="{% static 'css/img/Pepper P.jpg'%}" alt="G">
			<div class="container">
			<span>Gwyneth Paltrow</span>
			</div>
		</div>
	</div>
	<div class="column">
		<div class="card">
		<img src="{% static 'css/img/logan.jpg'%}" alt="H">
			<div class="container">
			<span>Hugh Jackman</span>
			</div>
		</div>
	</div>
	<div class="column">
		<div class="card">
		<img src="{% static 'css/img/Mark Strong.jpg'%}">
			<div class="container">
				<span>J.K Simmons</span>
			</div>
		</div>
	</div>
	<div class="column">
		<div class="card">
		<img src="{% static 'css/img/Willem D.png'%}">
			<div class="container">
				<span>Patrick Stewart</span>
			</div>
		</div>
	</div>
	<div class="column">
		<div class="card">
		<img src="{% static 'css/img/benedict cumberbatch.png'%}">
			<div class="container">
				<span>Benedict Quequmberbach</span>
			</div>
		</div>
	</div>
	<div class="column">
		<div class="card">
		<img src="{% static 'css/img/Tom Holland.jpg'%}" alt="T">
			<div class="container">
				<span>Tom Holland</span>
			</div>
		</div>
	</div>

</div>
<p>Hint: Inspect the Images</p>
</body>
</html>

game/templates/game/orcs.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>PYTHON GAME ARG</title>
<link rel="stylesheet" type="text/css"  href="{% static 'css/gamehome.css' %}">
</head>
<body>
<div align = "center" class="center">
<h1><font color="red">Final Question</font></h1>
<hr>
<h2>Vad var den första bokstaven i varje kod?</h2>
<hr>
</div>
</body>
</html>

game/templates/game/right.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>PYTHON GAME ARG</title>
<link rel="stylesheet" type="text/css"  href="{% static 'css/gamehome.css' %}">
</head>
<h1><font color="red">01000010 01101001 01101110 01100001 01110010 01111001</font></h1>
<div align = "center" class ="center">
	<p>01010100 01101000 01100101 00100000 01100001 01101110 01110011 01110111 01100101 01110010 00100000 01110100 01101111 00100000 01110100 01101000 01100101 00100000 01101110 01100101 01111000 01110100 00100000 01110100 01101000 01101001 01110011 00100000 01110001 01110101 01100101 01110011 01110100 01101001 01101111 01101110 00100000 01101001 01110011 00100000 01100110 01101111 01110101 01101110 01100100 00100000 01100001 01110100 00100000 01110100 01101000 01100101 00100000 01100101 01101110 01100100</p>
</div>

<p>01101000 01101001 01101110 01110100 : 01101001 01110100 01110011 00100000 01100001 01110100 00100000 01110100 01101000 01100101 00100000 01100101 01101110 01100100 0001010</p>
</body>
</html>

game/templates/game/zero.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>PYTHON GAME ARG</title>
<link rel="stylesheet" type="text/css"  href="{% static 'css/gamehome.css' %}">
</head>
<body>
<h1>" "</h1>
<div align = "center" class="center">
<hr>
<p>"For Doomhammer!"</p>
<hr>
<p>"We are the HORDE. We are slaves to nothing and no one!"</p>
<hr>
<p>"Thrall... the blood haze has lifted... the demon's fire has burnt out in my veins....I...have...freed...myself..."</p>
<hr>
<p>"Drink Hellscream...Claim your destiny. You will all be conquerors."</p>
<hr>
<p>"Looks like meat's back on the menu boys!"</p>



</div>
<p>Hint: All said by.</p>
</body>
</html>

shop/templates/npcshop/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}On-line Shop{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body style="background-color:lightgrey;">
{% include 'npcshop/navbar.html' %}

{% block content %}

{% endblock %}

<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
</body>
</html>

shop/templates/npcshop/detail.html
{% extends 'npcshop/base.html' %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }} {% else %} Products {% endif %}
{% endblock %}

{% block content %}
   <div class="container">
      <div class="row" style="margin-top: 6%">

        <div class="col-sm-8 blog-main">

          <div class="blog-post">
              <div class="row">
                <div class="card">
                    <div class="card-body">
                        <div class="col-md-6 text-right">
                            <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" style="height: 170px; width: auto">
                        </div>
                        <div class="col-md-6" style="padding-left: 20px">
                            <h3>{{ product.name }}</h3>
                            <h6><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h6>
                            <p class="text-muted">{{ product.price }} Gold</p>
                            <form action="{% url "cart:cart_add" product.id %}" method="post">
                                {% csrf_token %}
                                {{ cart_product_form }}
                                <input type="submit" value="add to cart" class="btn btn-primary">
                            </form>
                            <p>{{ product.description|safe|linebreaksbr }}</p>
                        </div>
                    </div>
                </div>
              </div>


          </div><!-- /.blog-post -->

        </div><!-- /.blog-main -->
      </div><!-- /.row -->

    </div><!-- /.container -->
{% endblock %}

shop/templates/npcshop/list.html
{% extends 'npcshop/base.html' %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }} {% else %} Products {% endif %}
{% endblock %}

{% block content %}
   <div class="container-fluid">
      <div class="row" style="margin-top: 6%">

        <div class="col-sm-8 blog-main">

          <div class="blog-post">
              <div class="row">
                  {% for product in products %}
                      <div class="col-md-4, over">
                        <div class="thumbnail, centerer">
                            <a href="{{ product.get_absolute_url }}">
                                <img class="Centered" src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'css/img/default.png' %} {% endif %}" style="height: 350px">
                            </a>
                            <div class="caption">
                                <h3 class="text-center">
                                    <a href="{{ product.get_absolute_url }}" style="color: Red">{{ product.name }}</a>
                                </h3>
                                <p class="text-center" style="color: yellow">{{ product.price }} Gold</p>
                            </div>
                        </div>
                      </div>
                  {% endfor %}
              </div>


          </div><!-- /.blog-post -->

        </div><!-- /.blog-main -->

        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
          <div class="sidebar-module" style="color: Red">
            <h4>Categories</h4>
            <ol class="list-unstyled">
              <li {% if not category %} class="active"{% endif %}><a href="{% url 'shop:product_list' %}">All</a></li>
            {% for c in categories %}

              <li {% if category.slug == c.slug %} class="active"{% endif %}>
                  <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
              </li>
            {% endfor %}
            </ol>
          </div>
        </div><!-- /.blog-sidebar -->

      </div><!-- /.row -->

    </div><!-- /.container -->
{% endblock %}

shop/templates/npcshop/navbar.html
{% load static %}
<nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="margin-bottom: 0px; background-color: black;">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="container-fluid">
      <div class="navbar-header">
    <a class="navbar-brand" href="{% url 'shop:product_list' %}" style="color: Gold">BACKGROUND NPC SHOP</a>
	</div>
  </div>
</nav>

shop/templates/npcshop/product/detail.html
{% extends 'npcshop/base.html' %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }} {% else %} Products {% endif %}
{% endblock %}

{% block content %}
   <div class="container">
      <div class="row" style="margin-top: 6%">
        <div class="col-sm-8 blog-main">
          <div class="blog-post">
              <div class="row">
                <div class="card">
                    <div class="card-body">
                        <div class="col-md-6 text-right">
                            <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/default.jpg' %} {% endif %}" style="height: 170px; width: auto">
                        </div>
                        <div class="col-md-6" style="padding-left: 20px">
                            <h3>{{ product.name }}</h3>
                            <h6><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h6>
                            <p class="text-muted">{{ product.price }} Gold</p>
                            <form action="{% url "cart:cart_add" product.id %}" method="post">
                                {{ cart_product_form }}
				{% csrf_token %}
                                <input type="submit" value="add to cart" class="btn btn-primary">
                            </form>
                            <p>{{ product.description|safe|linebreaks }}</p>
                        </div>
                    </div>
                </div>
              </div>


          </div><!-- /.blog-post -->

        </div><!-- /.blog-main -->
      </div><!-- /.row -->

    </div><!-- /.container -->
{% endblock %}

shop/templates/npcshop/product/list.html
{% extends 'npcshop/base.html' %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }} {% else %} Products {% endif %}
{% endblock %}

{% block content %}
   <div class="container-fluid">
      <div class="row" style="margin-top: 6%">

        <div class="col-sm-8 blog-main">

          <div class="blog-post">
              <div class="row">
                  {% for product in products %}
                      <div class="col-md-4, over">
                        <div class="thumbnail, centerer">
                            <a href="{{ product.get_absolute_url }}">
                                <img class="Centered" src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'css/img/default.png' %} {% endif %}" style="height: 350px">
                            </a>
                            <div class="caption">
                                <h3 class="text-center">
                                    <a href="{{ product.get_absolute_url }}" style="color: Red">{{ product.name }}</a>
                                </h3>
                                <p class="text-center" style="color: yellow">{{ product.price }} Gold</p>
                            </div>
                        </div>
                      </div>
                  {% endfor %}
              </div>


          </div><!-- /.blog-post -->

        </div><!-- /.blog-main -->

        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
          <div class="sidebar-module" style="color: Red">
            <h4>Categories</h4>
            <ol class="list-unstyled">
              <li {% if not category %} class="selected"{% endif %}><a href="{% url "shop:product_list" %}">All</a></li>
            {% for c in categories %}

              <li {% if category.slug == c.slug %} class="selected"{% endif %}>
                  <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
              </li>
            {% endfor %}
            </ol>
          </div>
        </div><!-- /.blog-sidebar -->

      </div><!-- /.row -->

    </div><!-- /.container -->
{% endblock %}